version: "3"
services:
  postgres:
    container_name: zabbix_psqldb
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=typeyoursecretpasswordhere
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /var/dockers/zabbix_psqldb/data:/var/lib/postgresql/data
    restart: always
  
  zabbixserver:
    container_name: zabbix_server
    build: 
      context: build/zabbix_server/
      dockerfile: Dockerfile
    environment:
      - DB_SERVER_HOST=zabbix_psqldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=typeyoursecretpasswordhere
    ports:
      - 10051:10051
    depends_on:
      - postgres
    restart: always

  zabbixweb:
    container_name: zabbix_web
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-3.2.4
    environment:
      - ZBX_SERVER_HOST=zabbix_server
      - DB_SERVER_HOST=zabbix_psqldb
      - POSTGRES_USER=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_PASSWORD=typeyoursecretpasswordhere
      - TZ=Europe/Istanbul
      - ZBX_SERVER_NAME=Pardus
    ports:
      - 80:80
      - 443:443
    depends_on:
      - zabbixserver
    restart: always
